{% set version = '1.11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bbmisc
  version: {{ version|replace("-", "_") }}

source:
  fn: BBmisc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/BBmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BBmisc/BBmisc_{{ version }}.tar.gz
  sha256: 1ea48c281825349d8642a661bb447e23bfd651db3599bf72593bfebe17b101d2

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-checkmate >=1.8.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-checkmate >=1.8.0

test:
  commands:
    - $R -e "library('BBmisc')"           # [not win]
    - "\"%R%\" -e \"library('BBmisc')\""  # [win]

about:
  home: https://github.com/berndbischl/BBmisc
  license: BSD_2_clause
  summary: Miscellaneous helper functions for and from B. Bischl and some other guys, mainly
    for package development.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
