# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rmTt1pkT4poHKqavSm2tW27WIb8HnVuv9EbZ30/1Hrx18eqFyXeHAIPZpr/YHtCM9ZaTKRnKlorPbC/WrWryVzATVXnVajUDAICSPbAOqLk9tkyWz8YvTti3EKqq7iljt9OCJBejtZyWiBerEQKIRNghaUhBB8JR4gMQtdwL5NKoPrBTaVK+/JXTeKqB1tNIGq4t2kR1rkp09bBPuA/t8klbb6VOhCKcefkGEVKofOVrafmbArMtsiPZb3TL+w4uR4KABus5iy64WUflX2HuQI7vNJbQCNZ3jLo/yaS8PU9nbbx0f/b/pm6PQBItGxXBpISPTRzdu7t/bhgvNbvaPLqtppiivGSMqflIMou82DrE9e4J6v3YPjH0SDxZI9RU0/9Y3cYeQme/HmL2hxMu7PQbiY5gVPp873gWI0BPWvp+AC+PpLncTMdOnJ3tpMmT0mIahHnogz6eWiocIhYGz5yCW5zMMBy8Oo0YsdbkuSaeSS+faZNqT6N1sMmLME0N4Xr5PTAq5c/e8XhvtCHpsEvH8QzmEB1rMKpdAQZozVt4EbYY2DpPMHcgXyxtyV5jdAsPXq704BR+IK9VO1FYq0cv0DU8vvnf7nM57Uq8Tk+8FEhUaRSh05q5BNM8LwUh+RdijW+FQnhbZqq6lo2iqP5SO5hjI48NecSMmhx8kaM="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_r_base3.6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_r_base4.0target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi