# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rmTt1pkT4poHKqavSm2tW27WIb8HnVuv9EbZ30/1Hrx18eqFyXeHAIPZpr/YHtCM9ZaTKRnKlorPbC/WrWryVzATVXnVajUDAICSPbAOqLk9tkyWz8YvTti3EKqq7iljt9OCJBejtZyWiBerEQKIRNghaUhBB8JR4gMQtdwL5NKoPrBTaVK+/JXTeKqB1tNIGq4t2kR1rkp09bBPuA/t8klbb6VOhCKcefkGEVKofOVrafmbArMtsiPZb3TL+w4uR4KABus5iy64WUflX2HuQI7vNJbQCNZ3jLo/yaS8PU9nbbx0f/b/pm6PQBItGxXBpISPTRzdu7t/bhgvNbvaPLqtppiivGSMqflIMou82DrE9e4J6v3YPjH0SDxZI9RU0/9Y3cYeQme/HmL2hxMu7PQbiY5gVPp873gWI0BPWvp+AC+PpLncTMdOnJ3tpMmT0mIahHnogz6eWiocIhYGz5yCW5zMMBy8Oo0YsdbkuSaeSS+faZNqT6N1sMmLME0N4Xr5PTAq5c/e8XhvtCHpsEvH8QzmEB1rMKpdAQZozVt4EbYY2DpPMHcgXyxtyV5jdAsPXq704BR+IK9VO1FYq0cv0DU8vvnf7nM57Uq8Tk+8FEhUaRSh05q5BNM8LwUh+RdijW+FQnhbZqq6lo2iqP5SO5hjI48NecSMmhx8kaM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
