appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rmTt1pkT4poHKqavSm2tW27WIb8HnVuv9EbZ30/1Hrx18eqFyXeHAIPZpr/YHtCM9ZaTKRnKlorPbC/WrWryVzATVXnVajUDAICSPbAOqLk9tkyWz8YvTti3EKqq7iljt9OCJBejtZyWiBerEQKIRNghaUhBB8JR4gMQtdwL5NKoPrBTaVK+/JXTeKqB1tNIGq4t2kR1rkp09bBPuA/t8klbb6VOhCKcefkGEVKofOVrafmbArMtsiPZb3TL+w4uR4KABus5iy64WUflX2HuQI7vNJbQCNZ3jLo/yaS8PU9nbbx0f/b/pm6PQBItGxXBpISPTRzdu7t/bhgvNbvaPLqtppiivGSMqflIMou82DrE9e4J6v3YPjH0SDxZI9RU0/9Y3cYeQme/HmL2hxMu7PQbiY5gVPp873gWI0BPWvp+AC+PpLncTMdOnJ3tpMmT0mIahHnogz6eWiocIhYGz5yCW5zMMBy8Oo0YsdbkuSaeSS+faZNqT6N1sMmLME0N4Xr5PTAq5c/e8XhvtCHpsEvH8QzmEB1rMKpdAQZozVt4EbYY2DpPMHcgXyxtyV5jdAsPXq704BR+IK9VO1FYq0cv0DU8vvnf7nM57Uq8Tk+8FEhUaRSh05q5BNM8LwUh+RdijW+FQnhbZqq6lo2iqP5SO5hjI48NecSMmhx8kaM=}
