travis:
  secure:
    BINSTAR_TOKEN: YDumsVPoC0IkqL/R8d2AvwEgup3ZoHP7bME/2kTYxEGDxsM2Qr69qXM1R5jByzjOzErVP3MfChbcWikxnQyFqDt64dCKISzR47c6+oCHPyFd4E1v2IqGW9ZvDv7Ei10bJbYR8l6cuimJJwvI4oMhpMEkT+mTkTZ7IihhBgdmxjy7/G7VvlVcr9RSP4cOI752SzVbUWVDqfWYRkqPp3kD0MbBOUXYD+4Fx58KPmIW8sTZdQRgijHgAKizp6izvc77HUX8KJw9DhZQ6p5vlEiSh5tZDIHI7/tPwCptZJ9bFO2zFf1Sp04bzZmWBNXjfHF5zYtcDhmanWjqeYLxuWEoxgeL9ky4qbDdWwloS450nOr3UUhElyxWpNc8aR+x9R7bgkJaP8YOoJqe+2d/K8xscxec2KxhON+7K8+BardlzRe6xAXX/eDDmGX6j5CWU4nEr0x76R8QRFntLAY3bsHtOubjjo1TEyt+hhwept0XE32gpL9JlNY1L0L2E3IAuqJah2Kn1sq0HQlEXp2wL7R7AsdJLk5NWUz9s+Wn4gPx8HRspfLRJRgJv1/o/V2aY2zuOpqJZ1o2AOJxp4B26wv8zA7XMerA8/Y7m0wd+7GPoEnvpslicJGySAetrQONe26D9LfZUjmHZEZ+s8djBHz97vpSGny6eeXgoWUnsKh4z58=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
